src/main/java/com/eucalyptus/tests/awssdk/TestBillingUsage.groovy
Test for EUCA-12976 (view usage apis for billing)
=> Portal service settings test

build.gradle, docker/Dockerfile, docker/README.md, n4j.sh, src/main/java/com/eucalyptus/tests/awssdk/N4j.java, src/main/java/com/eucalyptus/tests/awssdk/TestEC2ImageRegistration.groovy
Add Dockerfile, test runner script and cache configuration to support running tests via docker.
=> Docker image build

src/main/java/com/eucalyptus/tests/awssdk/N4j.java, src/main/java/com/eucalyptus/tests/awssdk/TestELBEC2Instance.groovy, src/main/java/com/eucalyptus/tests/suites/AllGoodSuite.java, src/main/java/com/eucalyptus/tests/suites/ElbFullSuite.java, src/main/java/com/eucalyptus/tests/suites/ElbShortSuite.java
Update elb request handling test and add to new elb full test suite.
=> ELB request test, add full suite for elb

src/main/java/com/eucalyptus/tests/awssdk/N4j.java, src/main/java/com/eucalyptus/tests/awssdk/TestEC2InstanceBundle.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestELBEC2Instance.groovy, src/main/java/com/eucalyptus/tests/suites/AllGoodSuite.java, src/main/java/com/eucalyptus/tests/suites/Ec2FullSuite.java, src/main/java/com/eucalyptus/tests/suites/Ec2ShortSuite.java, src/main/java/com/eucalyptus/tests/suites/ElbFullSuite.java, src/main/java/com/eucalyptus/tests/suites/ElbShortSuite.java
Add test for ec2 instance bundling and add to new ec2 full test suite.
=> Topic ec2 bundle instance test

src/main/java/com/eucalyptus/tests/awssdk/N4j.java, src/main/java/com/eucalyptus/tests/awssdk/TestAutoScalingDescribeInstances.java, src/main/java/com/eucalyptus/tests/awssdk/TestAutoScalingLaunchAndTerminate.java, src/main/java/com/eucalyptus/tests/awssdk/TestAutoScalingSuspendAndResumeProcesses.java
Fix delay when waiting for instance termination.
=> Auto scaling fix wait for instance termination

src/main/java/com/eucalyptus/tests/awssdk/UpTest.groovy, src/main/java/com/eucalyptus/tests/suites/InitializationSuite.java
Ensure services are up as first test in initialization suite
=> InitializationSuite now ensures services are available

src/main/java/com/eucalyptus/tests/awssdk/TestELBEC2Instance.groovy
Ensure the instance launched for registration to the elb runs in the enabled availability zone.
=> ELB EC2 instance launched in enabled zone

src/main/java/com/eucalyptus/tests/awssdk/TestCFTemplatesFull.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestELBEC2Instance.groovy, src/main/java/com/eucalyptus/tests/suites/AllGoodSuite.java, src/main/java/com/eucalyptus/tests/suites/AllShortSuite.java, src/main/java/com/eucalyptus/tests/suites/CloudFormationFullSuite.java, src/main/java/com/eucalyptus/tests/suites/CloudFormationShortSuite.java, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_ec2_meta.json, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_iam.json, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_instance_volumes.json, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_s3_buckets.json, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_trinity.json, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_vpc_meta.json
CloudFormation template tests for use in full suite.
=> CloudFormation template tests

build.gradle, src/main/java/com/eucalyptus/tests/awssdk/InitializationTest.groovy, src/main/java/com/eucalyptus/tests/awssdk/N4j.java, src/main/java/com/eucalyptus/tests/awssdk/TestEC2EbsImageRegistration.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestEC2ImageRegistration.groovy, src/main/java/com/eucalyptus/tests/load/EbsInstanceChurnLoadTest.groovy, src/main/java/com/eucalyptus/tests/load/InstanceChurnLoadTest.groovy, src/main/java/com/eucalyptus/tests/load/LoadBalancerChurnLoadTest.groovy, src/main/java/com/eucalyptus/tests/load/ObjectChurnLoadTest.groovy, src/main/java/com/eucalyptus/tests/load/StackChurnLoadTest.groovy, src/main/java/com/eucalyptus/tests/suites/EbsImageSuite.java, src/main/java/com/eucalyptus/tests/suites/LoadSuite.java
Test suite for load testing with some coverage for ec2, ebs, elb, cloudformation, and s3. A supporting test/suite is added for ebs image registration.
=> Test suite for load testing

src/main/java/com/eucalyptus/tests/awssdk/N4j.java, src/main/java/com/eucalyptus/tests/awssdk/S3QuotaTest.groovy, src/main/java/com/eucalyptus/tests/suites/S3ShortSuite.java
Quota test for s3 including coverage of updated error message for access denial on resource creation.
=> S3 quota test

src/main/java/com/eucalyptus/tests/awssdk/N4j.java, src/main/java/com/eucalyptus/tests/awssdk/S3QuotaTest.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestAutoScalingEC2InstanceTerminationProtection.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestAutoScalingEC2VPC.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestCFTemplatesShort.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestEC2VPCDefaultVPC.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestEC2VPCQuotasLimits.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestEC2VPCResourceConditionPolicy.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestEC2VPCSecurityGroupEgressRules.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestEC2VPCSecurityGroups.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestEC2VPCSecurityGroupsInstancesAttributes.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestELBAdministration.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestELBAttributes.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestELBDefaultVPC.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestELBEC2Instance.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestELBIAMResource.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestELBTagging.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestELBVPC.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestS3IAMConditionKeyLocationConstraint.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestS3IAMConditionKeyVersionId.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestS3IAMConditionKeysForAclsAndGrants.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestS3IAMConditionKeysForPutObject.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestS3IAMConditionKeysPrefixAndDelimiter.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestSTSAssumeRolePolicy.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestSTSAssumeRoleWithWebIdentity.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestSTSGetAccessToken.java, src/main/java/com/eucalyptus/tests/awssdk/TestSTSGetImpersonationToken.java, src/main/java/com/eucalyptus/tests/suites/S3ShortSuite.java, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_instance_volumes.json
Merge devel-4.4 changes to devel.
=> Merge updates from 4.4 tests

src/main/java/com/eucalyptus/tests/suites/AutoScalingFullSuite.java
Auto scaling full test suite is updated to run the scaling instance termination protection test.
=> Add scaling termination protection test to autoscaling full suite

src/main/java/com/eucalyptus/tests/awssdk/TestCFTemplatesFull.groovy, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_iam_managed_policies.json, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_iam_names.json, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_s3_bucket_policy.json
Add templates to the cloudformation full test suite covering:
- S3 bucket policy
- IAM named resources
- IAM managed policies
=> CloudFormation template tests for s3 bucket policy and iam

src/main/java/com/eucalyptus/tests/awssdk/TestCFTemplatesFull.groovy, src/main/java/com/eucalyptus/tests/suites/CloudFormationFullSuite.java, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_trinity.json
Update the cloud formation template used for testing elb so it has coverage for policies and cloud watch metrics.
=> CloudFormation template elb cookie policy and cloudwatch metric coverage

src/main/java/com/eucalyptus/tests/awssdk/TestCFTemplateLifecycle.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestCFTemplatesShort.groovy, src/main/java/com/eucalyptus/tests/suites/CloudFormationFullSuite.java
CloudFormation stack lifecycle test added with an initial test for retaining resources on delete. This may be slow so is added to the full suite.
Corymbia/eucalyptus#81
=> CloudFormation test for retaining stack resources on delete

src/main/resources/com/eucalyptus/tests/awssdk/cf_template_vpc_meta.json
CloudFormation test coverage for split and cidr intrinsic functions
=> CloudFormation test coverage for split and cidr intrinsic functions

src/main/java/com/eucalyptus/tests/awssdk/TestCFTemplatesFull.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestCFTemplatesShort.groovy, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_shortform.yaml, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_syntax.yaml
CloudFormation YAML template format coverage.
=> CloudFormation YAML template format test

src/main/java/com/eucalyptus/tests/awssdk/N4j.java, src/main/java/com/eucalyptus/tests/awssdk/TestEC2EbsImageRegistration.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestELBEC2EBSInstance.groovy
Added ELB EC2 instance test which will run if an ebs image is available. This test should be added to the elb full test suite but it currently fails due to ec2 reporting an incorrect status for starting instances (which show as pending)
Corymbia/eucalyptus#79
=> CloudFormation test coverage for elb ebs instance stop/start status

src/main/java/com/eucalyptus/tests/awssdk/N4j.java, src/main/java/com/eucalyptus/tests/awssdk/TestAutoScalingAdministration.java, src/main/java/com/eucalyptus/tests/awssdk/TestAutoScalingEC2InstanceTerminationProtection.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestAutoScalingEC2VPC.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestAutoScalingVMTypeReferenceValidation.java, src/main/java/com/eucalyptus/tests/awssdk/TestCFTemplatesFull.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestCFTemplatesShort.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestEC2Api.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestEC2EbsImageRegistration.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestEC2InstanceBundle.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestEC2VPCSecurityGroupsInstancesAttributes.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestMultipleSecurityGroups.groovy, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_ec2_signal_resource.json, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_trinity.json
Update tests to use instance type available on the cloud under test.
=> EC2 instance type detection

src/main/java/com/eucalyptus/tests/awssdk/TestCFTemplatesShort.groovy, src/main/java/com/eucalyptus/tests/awssdk/TestEC2IAMConditionKeys.groovy, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_ec2_meta.json
CloudFormation tests are updated to add coverage for security group permission descriptions.
=> EC2 security groups permission description test coverage

src/main/java/com/eucalyptus/tests/awssdk/TestCFTemplatesFull.groovy, src/main/resources/com/eucalyptus/tests/awssdk/cf_template_iam_names.json
Update CloudFormation full templates test with coverage for IAM managed policy names.
=> IAM managed policy name test coverage
